[package]
name = "fernet_cracker"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22"
clap = { version = "4.5", features = ["derive"] }
crossbeam-channel = "0.5"
ctrlc = "3.4"
fernet = "0.2"
indicatif = "0.17"
num_cpus = "1.16"
sha2 = "0.10"
crossterm = "0.27"
